<br>

<span style="font-size: 40px; color: grey; border: 1px dashed grey; padding:5 px"> Capstone Notebook </span>

_This is my new notebook made in entirety to fulfil only one purpose in my life that is, to complete the capstone project and_ `learn Data Science.` _Click on contents to navigate in the Notebook._

<p style="font-size: 20px; font-family:Book Antiqua ;">
            Content:
</p>
<br>
<a href="#Que1" style="color: Blue; font-size: 18px;">Question 1</a>
<br>
<a href="#Que2" style="color: Blue; font-size: 18px;">Question 2</a>
<br>
<a href="#Que3" style="color: Blue; font-size: 18px;">Question 3</a>

<a id="Que1"></a>

# Question 1:
<ol>
    <li> <a href="#gettingdata" >
        <p style="font-size: 15px; color: purple; font-family:Book Antiqua ;">
            Getting Data from Wikipedia page
        </p>
        </a>
    </li>
   <br>
     <li> <a href="#cleaning" >
        <p style="font-size: 15px; color: purple; font-family:Book Antiqua ;">
            Cleaning the data
        </p>
        </a>
    </li>
   <br>
    <li> <a href="#Printing" >
        <p style="font-size: 15px; color: purple; font-family:Book Antiqua ;">
            Printing Shape of last dataframe
        </p>
        </a>
    </li>
</ol>


1. Start by creating a new Notebook for this assignment.
2. Use the Notebook to build the code to scrape the following Wikipedia page, https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M, in order to obtain the data that is in the table of postal codes and to transform the data into a pandas dataframe like the one shown below:
<img src="https://d3c33hcgiwev3.cloudfront.net/imageAssetProxy.v1/7JXaz3NNEeiMwApe4i-fLg_40e690ae0e927abda2d4bde7d94ed133_Screen-Shot-2018-06-18-at-7.17.57-PM.png?expiry=1586131200000&hmac=jvHsOwv4YDzS4RLLurPuNMiqk6oF-lUrohIKO0kfSDE"></img>
3. To create the above dataframe:

 * The dataframe will consist of three columns: PostalCode, Borough, and Neighborhood
 * Only process the cells that have an assigned borough. Ignore cells with a borough that is Not assigned.
 * More than one neighborhood can exist in one postal code area. For example, in the table on the Wikipedia page, you will notice that M5A is listed twice and has two neighborhoods: Harbourfront and Regent Park. These two rows will be combined into one row with the neighborhoods separated with a comma as shown in row 11 in the above table.
 * If a cell has a borough but a Not assigned neighborhood, then the neighborhood will be the same as the borough.
 * Clean your Notebook and add Markdown cells to explain your work and any assumptions you are making.
 * In the last cell of your notebook, use the .shape method to print the number of rows of your dataframe.

In [2]:
%%capture
# Now I shall enchant all the mighty python libraries
! pip install wikipedia
! pip install geocoder
import pandas as pd 
import numpy as np

<a id='gettingdata'></a>

### Getting Data from Wikipedia:
* **Converting it into pandas dataframe**

In [66]:
import wikipedia as wp

html = wp.page("List_of_postal_codes_of_Canada:_M").html().encode("UTF-8")
df = pd.read_html(html)[0]
#df.to_csv('PostalCodes.csv',header=0,index=False)
df.head(10)

  Postal code           Borough                                  Neighborhood
0         M1A      Not assigned                                           NaN
1         M2A      Not assigned                                           NaN
2         M3A        North York                                     Parkwoods
3         M4A        North York                              Victoria Village
4         M5A  Downtown Toronto                    Regent Park / Harbourfront
5         M6A        North York             Lawrence Manor / Lawrence Heights
6         M7A  Downtown Toronto  Queen's Park / Ontario Provincial Government
7         M8A      Not assigned                                           NaN
8         M9A         Etobicoke                              Islington Avenue
9         M1B       Scarborough                               Malvern / Rouge

<a id="cleaning"></a>

### Let's clean this shit up:
* **cleaning dataframe**

In [67]:
# make backup of dataframe
ndf= df.copy(deep= True)

In [68]:
# replace all borough value "Not assigned" with Nan
import numpy as np
df["Borough"].replace("Not assigned", np.nan, inplace= True)
df.head(10)

  Postal code           Borough                                  Neighborhood
0         M1A               NaN                                           NaN
1         M2A               NaN                                           NaN
2         M3A        North York                                     Parkwoods
3         M4A        North York                              Victoria Village
4         M5A  Downtown Toronto                    Regent Park / Harbourfront
5         M6A        North York             Lawrence Manor / Lawrence Heights
6         M7A  Downtown Toronto  Queen's Park / Ontario Provincial Government
7         M8A               NaN                                           NaN
8         M9A         Etobicoke                              Islington Avenue
9         M1B       Scarborough                               Malvern / Rouge

In [69]:
# Check missing values
def check_missing(df):
    l=[]
    missing_data = df.isnull()
    for column in missing_data.columns.values.tolist():
        k=missing_data[column].value_counts().to_frame()
        l.append(k)
    return(l)
for i in check_missing(df):
    print(i)

       Postal code
False          180
       Borough
False      103
True        77
       Neighborhood
False           103
True             77

In [70]:
# Remove all the rows with Borough value a NaN
df.dropna(subset = ["Borough"], inplace =True)
df.reset_index(drop= True, inplace = True)
df.rename(columns={"Postal code":"PostalCode"}, inplace= True, errors ="raise")
df.head(10)

  PostalCode           Borough                                  Neighborhood
0        M3A        North York                                     Parkwoods
1        M4A        North York                              Victoria Village
2        M5A  Downtown Toronto                    Regent Park / Harbourfront
3        M6A        North York             Lawrence Manor / Lawrence Heights
4        M7A  Downtown Toronto  Queen's Park / Ontario Provincial Government
5        M9A         Etobicoke                              Islington Avenue
6        M1B       Scarborough                               Malvern / Rouge
7        M3B        North York                                     Don Mills
8        M4B         East York              Parkview Hill / Woodbine Gardens
9        M5B  Downtown Toronto                      Garden District, Ryerson

In [71]:
# Removed all missing value
for i in check_missing(df):
    print(i)

       PostalCode
False         103
       Borough
False      103
       Neighborhood
False           103

<a id="Printing"></a>

### Printing shape of dataframe:

In [72]:
df.shape

(103, 3)

<a id="Que2"></a>

# Question 2:
<ol>
    <li> <a href="#latlon" >
        <p style="font-size: 15px; color: purple; font-family:Book Antiqua ;">
            Getting lat lon of all postal codes
        </p>
        </a>
    </li>
   <br>
    <li> <a href="#merge" >
        <p style="font-size: 15px; color: purple; font-family:Book Antiqua ;">
            Merging the value of lat lng with main data Frame
        </p>
        </a>
    </li>
</ol>

<ul>
    <li>
        Now that you have built a dataframe of the postal code of each neighborhood along with the borough name and neighborhood name, in order to utilize the Foursquare location data, we need to get the latitude and the longitude coordinates of each neighborhood.</li>
    </ul>

<a id="latlon"></a>

### Getting the latitide and longitude of all postal location:

In [73]:
''''import geocoder # import geocoder

# initialize your variable to None
lat_lng_coords = None

# loop until you get the coordinates
latitude, longitude = [],[]
for postal_code in df["PostalCode"]:
    
    g = geocoder.google('{}, Toronto, Ontario'.format(str(postal_code)))
    lat_lng_coords = g.latlng
    if(lat_lng_coords):
        latitude.append(lat_lng_coords[0])
        longitude.append(lat_lng_coords[1])
                            
print(latitude, longitude)'''
dfl= pd.read_csv("Geospatial_Coordinates.csv")

#dfl.sort_values(['Postal Code'], axis= 0, inplace= True)
dfl

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
..          ...        ...        ...
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

<a id="merge"></a>

### Adding the lat lng in the main Data Frame:

In [74]:
dfl.rename(columns={"Postal Code":"PostalCode"}, inplace= True, errors ="raise")

In [75]:
df = pd.merge(df, dfl, how='outer', on=['PostalCode', 'PostalCode'])
df.head(20)

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,Regent Park / Harbourfront,43.654260,-79.360636
3,M6A,North York,Lawrence Manor / Lawrence Heights,43.718518,-79.464763
4,M7A,Downtown Toronto,Queen's Park / Ontario Provincial Government,43.662301,-79.389494
5,M9A,Etobicoke,Islington Avenue,43.667856,-79.532242
6,M1B,Scarborough,Malvern / Rouge,43.806686,-79.194353
7,M3B,North York,Don Mills,43.745906,-79.352188
8,M4B,East York,Parkview Hill / Woodbine Gardens,43.706397,-79.309937
9,M5B,Downtown Toronto,"Garden District, Ryerson",43.657162,-79.378937
10,M6B,North York,Glencairn,43.709577,-79.445073
11,M9B,Etobicoke,West Deane Park / Princess Gardens / Martin Gr...,43.650943,-79.554724
12,M1C,Scarborough,Rouge Hill / Port Union / Highland Creek,43.784535,-79.160497
13,M3C,North York,Don Mills,43.725900,-79.340923
14,M4C,East York,Woodbine Heights,43.695344,-79.318389
15,M5C,Downtown Toronto,St. James Town,43.651494,-79.375418
16,M6C,York,Humewood-Cedarvale,43.693781,-79.428191
17,M9C,Etobicoke,Eringate / Bloordale Gardens / Old Burnhamthor...,43.643515,-79.577201
18,M1E,Scarborough,Guildwood / Morningside / West Hill,43.763573,-79.188711
19,M4E,East Toronto,The Beaches,43.676357,-79.293031

<a id="Que3"></a>

# Question 3:

### importing necessary libraries

In [79]:
%%capture
import requests # library to handle requests
import pandas as pd # library for data analsysis
import numpy as np # library to handle data in a vectorized manner
import random # library for random number generation

!conda install -c conda-forge geopy --yes 
from geopy.geocoders import Nominatim # module to convert an address into latitude and longitude values

# libraries for displaying images
from IPython.display import Image 
from IPython.core.display import HTML 
    
# tranforming json file into a pandas dataframe library
from pandas.io.json import json_normalize

!conda install -c conda-forge folium=0.5.0 --yes
import folium # plotting library

print('Folium installed')
print('Libraries imported.')

### Define Foursquare Credentials and Version

In [78]:
CLIENT_ID = 'XQ4VC0KRBMPWI2SLFPPEXNRM4N4DQSWCMYYD0OQUJZFOLBKY' # your Foursquare ID
CLIENT_SECRET = 'MNTKKUSL4CL14SEVLATGBGLRQ1ZEPJEQJJ1I0PE5SWMOGKLI' # your Foursquare Secret
VERSION = '20200327'
LIMIT = 30
print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: XQ4VC0KRBMPWI2SLFPPEXNRM4N4DQSWCMYYD0OQUJZFOLBKY
CLIENT_SECRET:MNTKKUSL4CL14SEVLATGBGLRQ1ZEPJEQJJ1I0PE5SWMOGKLI